import { useState } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import { useQuery } from '@tanstack/react-query'
import { BookOpen, CheckCircle2, PlayCircle, Trophy, Brain, Cpu, ArrowRight } from 'lucide-react'
import api from '../services/api'
import ReactMarkdown from 'react-markdown'

export default function Learning() {
  const { repoId } = useParams()
  const navigate = useNavigate()
  const [selectedModuleId, setSelectedModuleId] = useState<string | null>(null)

  const { data: paths = [] } = useQuery({
    queryKey: ['learning-paths', repoId],
    queryFn: async () => (await api.get(`/api/learning/repositories/${repoId}/paths`)).data,
    enabled: !!repoId,
  })

  if (!repoId) {
    return (
      <div className="animate-fade-in" style={{ padding: 40, textAlign: 'center' }}>
        <Brain size={48} style={{ color: 'var(--brand-primary)', margin: '0 auto 16px' }} />
        <h2 style={{ marginBottom: 8 }}>Select a repository to start learning</h2>
        <p style={{ color: 'var(--text-secondary)', marginBottom: 24 }}>IBM Bob generates personalized learning paths for every connected codebase.</p>
      </div>
    )
  }

  const path = paths[0]
  if (!path) return <div className="spinner" style={{ margin: '40px auto' }} />

  const progress = path.progress?.[0]?.completedModules || []
  const activeModule = path.modules.find((m: any) => m.id === selectedModuleId) || path.modules[0]

  return (
    <div className="animate-fade-in" style={{ display: 'grid', gridTemplateColumns: '1fr 340px', gap: 32, margin: '-10px 0 0 0' }}>
      
      {/* Main Content Area */}
      <div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 24 }}>
          <div style={{ width: 48, height: 48, borderRadius: 'var(--radius-md)', background: 'var(--brand-glow)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
            <Cpu size={24} style={{ color: 'var(--brand-light)' }} />
          </div>
          <div>
            <div style={{ fontSize: '0.8rem', color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.05em', fontWeight: 600 }}>Generated by IBM Bob</div>
            <h1 style={{ fontSize: '1.5rem', marginBottom: 2 }}>{activeModule?.title || path.title}</h1>
          </div>
        </div>

        {activeModule && (
          <div className="glass-card" style={{ padding: 32, minHeight: 400 }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 24 }}>
              <span className={`badge ${activeModule.type === 'CHALLENGE' ? 'badge-rose' : activeModule.type === 'QUIZ' ? 'badge-amber' : 'badge-brand'}`}>
                {activeModule.type}
              </span>
              <span style={{ fontSize: '0.85rem', color: 'var(--text-muted)' }}>~{activeModule.estimatedMinutes} mins</span>
            </div>

            <div style={{ fontSize: '1rem', lineHeight: 1.7, color: 'var(--text-primary)' }}>
              <ReactMarkdown>{activeModule.content}</ReactMarkdown>
            </div>

            {activeModule.codeExamples?.map((ex: any, idx: number) => (
              <div key={idx} className="code-block" style={{ marginTop: 24 }}>
                <div className="code-block-header">{ex.title}</div>
                <pre><code>{ex.code}</code></pre>
              </div>
            ))}

            <div className="divider" style={{ margin: '32px 0' }} />
            
            <div className="flex justify-between items-center">
              <button className="btn btn-secondary">Previous</button>
              <button className="btn btn-primary" onClick={async () => {
                await api.post(`/api/learning/modules/${activeModule.id}/complete`, { timeSpentMinutes: 15 })
                window.location.reload()
              }}>
                Complete & Continue <ArrowRight size={16} />
              </button>
            </div>
          </div>
        )}
      </div>

      {/* Curriculum Sidebar */}
      <div style={{ position: 'sticky', top: 32, height: 'fit-content' }}>
        <h3 style={{ marginBottom: 16 }}>{path.title}</h3>
        <p style={{ fontSize: '0.85rem', color: 'var(--text-secondary)', marginBottom: 24 }}>{path.description}</p>
        
        <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
          {path.modules.map((m: any, i: number) => {
            const isCompleted = progress.includes(m.id)
            const isActive = activeModule?.id === m.id
            return (
              <div key={m.id} className={`module-card ${isCompleted ? 'completed' : ''}`}
                onClick={() => setSelectedModuleId(m.id)}
                style={{ borderColor: isActive ? 'var(--brand-primary)' : '' }}>
                <div className="flex items-start gap-3">
                  <div style={{ marginTop: 2 }}>
                    {isCompleted ? <CheckCircle2 size={18} style={{ color: 'var(--accent-green)' }} /> : 
                     m.type === 'CHALLENGE' ? <Trophy size={18} style={{ color: 'var(--accent-rose)' }} /> :
                     <PlayCircle size={18} style={{ color: isActive ? 'var(--brand-primary)' : 'var(--text-muted)' }} />}
                  </div>
                  <div>
                    <div style={{ fontWeight: 600, fontSize: '0.9rem', color: isActive ? 'var(--brand-light)' : 'var(--text-primary)' }}>
                      {i + 1}. {m.title}
                    </div>
                    <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)', marginTop: 4 }}>
                      {m.type} • {m.estimatedMinutes}m
                    </div>
                  </div>
                </div>
              </div>
            )
          })}
        </div>
      </div>
    </div>
  )
}
